name: TrapStats Weekly

on:
  schedule:
    - cron: "0 14 * * 1"   # Mondays 14:00 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run generator
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          OUT_DIR: out
          CACHE_DIR: .cache
        run: |
          python src/trapstats_runner.py --period weekly --title "TrapStats"
      - name: Commit artifacts
        run: |
          git config user.name "trapstats-bot"
          git config user.email "trapstats-bot@users.noreply.github.com"
          git add out/ .cache/
          git commit -m "automated: weekly report" || echo "nothing to commit"
          git push
